version: '3.0'

services:
  site:
    image: jekyll/jekyll:3.8
    container_name: ugommirikwe.com
    environment:
      - JEKYLL_ENV=development
    command: sh -c "bundle update && bundle exec jekyll serve --watch --force_polling --incremental --livereload --verbose --host=0.0.0.0"
    ports:
      - 4004:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll:Z
